### ISSUE TITLE
repo name?

### ISSUE THREAD

**Issue by arthurKocher** [grdspcht/ggarg#22]
I guess we would need to change the repo name to ggret

**Comment by grdspcht** [comment]
I've now changed the repo name to ggret. You can still see the old ggarg readme page if you navigate to [https://github.com/grdspcht/ggret/](https://github.com/grdspcht/ggret/) because all development changes - including changes to the readme page - are currently happening on the testing branch. Once we merge these branches again, we will see them reflected on the main page.
